### ISSUE TITLE
Could the ground truth 2D annotation of traffic signs also be provided?

### ISSUE THREAD

**Issue by BailiangJ** [hemangchawla/3d-groundtruth-traffic-sign-positions#1]
Hi, is it possible also to provide the 2D annotation of the traffic signs? Because we are also working on the 3D mapping of the traffic sign and we want to compare our results with yours.

Thanks!

**Comment by adrelino** [comment]
I would also be interested in the 2D bounding boxes used to triangulate the 3D sign positions. Is there any way you can share these or at least hint how they can be re-created?

**Comment by hemangchawla** [comment]
Hi @BailiangJ, @adrelino we have extracted bounding boxes from the mapillary dataset along with some of our own datasets to train our detection model. You may also look in the Swedish and the German traffic signs datasets. 

However, for you to compare, I have added the GT annotations of bboxes. 

Hope this helps.
